export const ENVIRONMENT = {
  STRIPE_PUBLISHABLE: process.env.REACT_APP_STRIPE_PUBLISHABLE,
  GRAPHQL_URL: process.env.REACT_APP_GRAPHQL_URL,
  DATA_SERVER_URL: process.env.REACT_APP_DATA_SERVER_URL,
  STRIPE_PRICE: process.env.REACT_APP_STRIPE_PRICE,
}
